#!/bin/bash

function cjd() {
	if [[ -n $1 ]]; then
		if [[ -n $(echo $1 | grep -E '^[0-9]0$') ]]; then
			cd ~/Documentos/${1}*
		elif [[ -n $(echo $1 | grep -E '^[0-9][1-9]$') ]]; then 
			cd ~/Documentos/*/${1}*
		elif [[ -n $(echo $1 | grep -E '^[0-9][1-9].[0-9][0-9]$') ]]; then 
			cd ~/Documentos/*/*/${1}* 
		fi 
	fi 
}
