#!/bin/sh

function main() {
	while :; do 
		case "${1-}" in 
			-h | --help) usage; exit 0;;
			-?*) echo -e "Opção desconhecida: ${1-}\n$(usage)\n"; exit 1 ;;
			*) break ;;
		esac
	done

	# One day I'll make it parse command line stuff, but like, not today 
	preinstall
	custom_scripts
	suckless
	custom_dotfiles
	general
	gamer
	programmer
}

function usage() {
	cat <<EOF
daninstaller: Personal Arch Post Install Script
by Dan 

Installs stuff I use on the daily 

USAGE: $(basename ${BASH_SOURCE[0]}) [OPTIONS]

OPTIONS:
	-h, --help:	Gets you here

EOF
}

function preinstall() {
	# Stuff I use to install other stuff 
	sudo pacman -Syyu 
	echo -e "[preinstall] System update finished"
}

function custom_scripts() {
	mkdir ~/.local/
	mkdir ~/.local/bin
	mkdir ~/.local/functions
	echo -e "[custom_scripts] Directories for local scripts created"

	cp ~/Downloads/dotfiles/scripts/* ~/.local/bin/
	cp ~/Downloads/dotfiles/functions/* ~/.local/functions/
	echo -e "[custom_scripts] Custom scripts added to proper folders"
}

function suckless() {
	mkdir ~/Downloads/suckless
	cd ~/Downloads/suckless
	echo -e "[suckless] suckless directory created"

	git clone https://git.suckless.org/dwm
	git clone https://git.suckless.org/st
	git clone https://git.suckless.org/surf
	git clone https://git.suckless.org/tabbed
	git clone https://git.suckless.org/dmenu
	echo -e "[suckless] tools cloned"
}

function custom_dotfiles() {
	cat ~/Downloads/dotfiles/bashrc >> ~/.bashrc
	cat ~/Downloads/dotfiles/xinitrc >> ~/.xinitrc

	mkdir ~/.config/nvim
	touch ~/.config/nvim/init.vim
	cat ~/Downloads/dotfiles/init.vim >> ~/.config/nvim/init.vim

	sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'


	echo -e "[custom_dotfiles] custom dotfiles appended to existing configs "
}

function gamer() {
	sudo pacman -S steam lutris gamemode wine-staging vkd3d 
	sudo yay -S leagueoflegends-git 
	echo -e "[gamer] Gamer stuff added"
}

function general() {
	sudo pacman -S xournalpp krita webapp-manager obs-studio 
	sudo yay -S librewolf-bin obsidian 
	echo -e "[general] General usage software added"
}

function programmer () {
	sudo pacman -S neovim
	sudo yay -S asdf-vm 
	echo -e "[general] Programmer stuff added"
}

function asdf_langs() {
	asdf plugin add python
	asdf plugin add java
	asdf plugin add rust 
	asdf plugin add R
	echo -e "[asdf_langs] Plugins added"

	asdf install python 3.10.0
	asdf install java openjdk-16
	asdf install rust latest 
	asdf install R latest 
	echo -e "[asdf_langs] Languages installed"
}

main "$@"
