#!/bin/bash

function main() {
	while true; do 
		xsetroot -name "$(danbar)"
		sleep 1
	done

}

function debug() {
	danbar 
}

function gpu_mode() {
	optimus-manager --print-mode | awk '{print "[GPU: " $5 "]"}'
}

function wlan_ip() {
	Res=$(ip addr show wlp2s0 | grep -m 1 inet)
	if [[ -n $Res ]]; then
		echo $Res | awk -F ' ' '{ print "[Wlan: " $2  "]"} '
	else
		echo "[Wlan: off]"
	fi 
}

function eth_ip() {
	Res=$(ip addr show enp3s0 | grep -m 1 inet)
	if [[ -n $Res ]]; then
		echo $Res | awk -F ' ' '{ print "[Eth: " $2 "]"}'
	else
		echo "[Eth: off]"
	fi
}

function lol_abi() {
	Abi=$(sysctl abi.vsyscall32 | awk -F '=' '{ print $2 }')
	if [[ $Abi == '0' ]]; then
		echo "[Lol: Ok]"
	else
		echo "[Lol: No]"
	fi
}

function dan_date() {
	date +"%X %x"
}

function danbar() {
	Gpu=$( gpu_mode )
	Wlan=$( wlan_ip )
	Eth=$( eth_ip )
	Lol=$( lol_abi )

	echo "$Gpu $Wlan $Eth $Lol $(dan_date)"
}

main "$@"
