#!/bin/bash

function main() { 

	while :; do
		case "${1-}" in
			-h | --help) usage; exit 0;;
			-d | --debug) danbar; exit 0;; 
			-?*) echo 'Mano'; exit 1 ;;
			*) break ;;
		esac
	done

	while true; do
		xsetroot -name "$(danbar)"
		sleep 2
	done 
} 

function danbar() {
	echo "$(lol) $(eth) $(date +'%D %T')"
}

function gpu() {
	optimus-manager --print-mode | awk '{print "[GPU: " $5 "]"}'
}

function lol() {
	if [[ $(sysctl abi.vsyscall32 | awk '/abi.vsyscall32 =/ {print $3}') == "0" ]]; then 
		echo -e "[LoL: Ok]"
	else 
		echo -e "[LoL: Nope]"
	fi
}

function eth() {
	echo -e "[Eth: $(ip addr show ens133 | awk '/inet / {print $2}')]"
}

function wifi() {
	echo -e "[Wifi: $(iwgetid -r) $(ip addr show wlp2s0 | awk '/inet / {print $2}')]" 
}

main "$@"
